import {
	PUBLIC_BACKEND_BASE_URL,
	PUBLIC_OF_API_BASE_URL,
	PUBLIC_OF_API_KEY
} from '$env/static/public';

export const BACKEND_BASE_URL = PUBLIC_BACKEND_BASE_URL;
export const ONLYFANS_API_KEY = PUBLIC_OF_API_KEY;
export const ONLYFANS_API_URL = PUBLIC_OF_API_BASE_URL;
